app = "splitter-gpu-service"
primary_region = "sjc" # San Jose, CA - modify as needed
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "9000"
  HOST = "0.0.0.0"
  CUDA_VISIBLE_DEVICES = "0"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  gpu_kind = "a100-40gb" # Use A100 GPU
  memory = "16gb"
  cpu_kind = "dedicated"
  cpus = 4