app = "splitter-backend"
primary_region = "sjc" # San Jose, CA - modify as needed
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  ENV = "production"
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"